export class Articulo {
    codigo: String;
    codmarca: number;
    codfamilia: number;
    pro_codigo: String;
    abrevunidadmedida: String;
    codgrupoarticulo: String;
    nomarticulo: String;
    preciosugerido: number;
    stockminimo: number;
    stockmaximo: number;
    puntoreorden: number;
    codigobarraprincipal: String;
    origen: String;
    imagen: String;
    nombimagen: String;
    status: String;
    alto: number;
    ancho: number;
    compuesto: boolean;
    costodirecto: number;
    costoreferencial: number;
    costoreposicion: number;
    descripcionlarga: String;
    empacado: boolean;
    fraccionado: boolean;
    facturable: boolean;
    pctdescuento: number;
    peso: number;
    profundidad: number;
    serializado: boolean;
    sinexistencia: boolean;
    tipoarticulo: String;
    tipocosto: String;
    ubicacion: String;
    ultimocosto: number;
    costoreal: number;
    descuentoprov1: number;
    descuentoprov2: number;
    descuentoprov3: number;
    descuentoprov4: number;
    costobase: number;
    tipodescuento: String;
    usacesta: boolean;
    precioporempaque: boolean;
    codtipoiva: String;
    codtipislr: number;
    codmoneda: number;
    codpresentacion: number;
    codtipo: number;
    codsabor: number;
    codnegocio: String;
    codvendedor: String;
    codlinea: number;
    aplicalista: boolean;
    merma: number;
    cantreorden: number;
    despostable: boolean;
    serial: String;
    fechaultcompra: String;
    color: String;
    nombrefamilia: String;
    nombregrupoarticulo: String;
    nombreunidadmedida: String;
    nombremarca: String;

    constructor(codigo: String,codmarca: number,codfamilia: number,pro_codigo: String, abrevunidadmedida: String,codgrupoarticulo: String, nomarticulo: String, preciosugerido: number, stockminimo: number,stockmaximo: number,puntoreorden: number, codigobarraprincipal: String,origen: String, imagen: String, nombimagen: String,status: String,alto: number,ancho: number,compuesto: boolean,costodirecto: number,costoreferencial: number,costoreposicion: number, descripcionlarga: String,  empacado: boolean, fraccionado: boolean,facturable: boolean,pctdescuento: number, peso: number,profundidad: number,serializado: boolean,sinexistencia: boolean,tipoarticulo: String,tipocosto: String,ubicacion: String, ultimocosto: number,costoreal: number,descuentoprov1: number, descuentoprov2: number, descuentoprov3: number, descuentoprov4: number,  costobase: number,tipodescuento: String,usacesta: boolean,precioporempaque: boolean,codtipoiva: String, codtipislr: number, codmoneda: number,codpresentacion: number,codtipo: number,codsabor: number,codnegocio: String, codvendedor: String,codlinea: number,aplicalista: boolean, merma: number,cantreorden: number, despostable: boolean,serial: String,fechaultcompra: String, color: String,nombrefamilia: String,nombregrupoarticulo: String,nombreunidadmedida: String,nombremarca: String) {


        this.codigo=codigo;
        this.codmarca= codmarca;
        this.codfamilia=codfamilia;
        this.pro_codigo=pro_codigo;
        this.abrevunidadmedida=abrevunidadmedida;
        this.codgrupoarticulo=codgrupoarticulo;
        this.nomarticulo=nomarticulo;
        this.preciosugerido=preciosugerido;
        this.stockminimo=stockminimo;
        this.stockmaximo=stockmaximo;
        this.puntoreorden=puntoreorden;
        this.codigobarraprincipal=codigobarraprincipal;
        this.origen=origen;
        this.imagen=imagen;
        this.nombimagen=nombimagen;
        this.status=status;
        this.alto=alto;
        this.ancho=ancho;
        this.compuesto=compuesto;
        this.costodirecto=costodirecto;
        this.costoreferencial= costoreferencial;
        this.costoreposicion= costoreposicion;
        this.descripcionlarga=descripcionlarga;
        this.empacado=empacado;
        this.fraccionado=fraccionado;
        this.facturable=facturable;
        this.pctdescuento=pctdescuento;
        this.peso=peso;
        this.profundidad=profundidad;
        this.serializado=serializado;
        this.sinexistencia=sinexistencia;
        this.tipoarticulo=tipoarticulo;
        this.tipocosto=tipocosto;
        this.ubicacion=ubicacion;
        this.ultimocosto=ultimocosto;
        this.costoreal=costoreal;
        this.descuentoprov1=descuentoprov1;
        this.descuentoprov2=descuentoprov2;
        this.descuentoprov3= descuentoprov3;
        this.descuentoprov4=descuentoprov4;
        this.costobase=costobase;
        this.tipodescuento=tipodescuento;
        this.usacesta=usacesta;
        this.precioporempaque=precioporempaque;
        this.codtipoiva= codtipoiva;
        this.codtipislr=codtipislr;
        this.codmoneda=codmoneda;
        this.codpresentacion=codpresentacion;
        this.codtipo=codtipo;
        this.codsabor=codsabor;
        this.codnegocio=codnegocio;
        this.codvendedor=codvendedor;
        this.codlinea=codlinea;
        this.aplicalista=aplicalista;
        this.merma=merma;
        this.cantreorden=cantreorden;
        this.despostable=despostable;
        this.serial=serial;
        this.fechaultcompra=fechaultcompra;
        this.color=color;
        this. nombrefamilia=nombrefamilia;
        this.nombregrupoarticulo=nombregrupoarticulo;
        this.nombreunidadmedida=nombreunidadmedida;
        this.nombremarca=nombremarca;

    }
}