export class Factura{
    numerofactura: String;
    codnegocio:String;
    fechaemision: Date;
    fechavencimiento: Date;
    tipoiva:String;
    codigoforma: String;
    codcliente: String;
    referencia: String;
    codvendedor: String;
    tarifa:String;
    destino: String;
    mn:String;
    viaje:String;
    fecha: String;
    shipper:String;
    consignee: String;
    status: String;
    baseimp: Number;
    baseimp_a: Number;
    baseimp_b: Number;
    baseimp_c:Number;
    baseimp_d: Number;
    baseimp_x: Number;
    baseimp_y: Number;
    isrl: Number;
    observacion: Number;
    numcontrol: String;
    numretencion: Number;
    pctiva_a: Number;
    pctiva_b: Number;
    pctiva_c: Number;
    pctiva_d:Number;
    status_cobro: String;
    tipodocumento: String;
    contable: String;
    numeroz: String;
    status_impresion: String;
    codigoruta: String;
    constructor(numfactura: String,codnegocio:String,femision: Date, fvencimiento: Date, tipoiva:String,codforma: String, codcliente: String,referencia: String, codvendedor: String,tarifa:String, destino: String, mn:String,viaje:String,fecha: String,shipper:String,consignee: String,status: String,baseimp: Number,baseimp_a: Number, baseimp_b: Number,baseimp_c:Number, baseimp_d: Number,baseimp_x: Number, baseimp_y: Number,isrl: Number, observacion: Number,numcontrol: String,numretencion: Number,pctiva_a: Number, pctiva_b: Number,pctiva_c: Number, pctiva_d:Number,status_cobro: String,tipodocumento: String,contable: String, numeroz: String,status_impresion: String, codigoruta: String)
    {

        this.numerofactura=numfactura;
        this.codnegocio=codnegocio;
        this.fechaemision=femision;
        this.fechavencimiento=fvencimiento;
        this.tipoiva=tipoiva;
        this.codigoforma= codforma;
        this.codcliente=codcliente;
        this.referencia= referencia;
        this.codvendedor=codvendedor;
        this.tarifa=tarifa;
        this.destino=destino;
        this.mn=mn ;
        this.viaje=viaje;
        this.fecha=fecha;
        this.shipper=shipper;
        this.consignee=consignee;
        this.status=status;
        this.baseimp=baseimp;
        this.baseimp_a=baseimp_a;
        this.baseimp_b =baseimp_b;
        this.baseimp_c=baseimp_c;
        this.baseimp_d=baseimp_d;
        this.baseimp_x=baseimp_x;
        this.baseimp_y=baseimp_y;
        this.isrl=isrl;
        this.observacion=observacion;
        this.numcontrol=numcontrol;
        this.numretencion=numretencion;
        this.pctiva_a=pctiva_a;
        this.pctiva_b=pctiva_b;
        this.pctiva_c=pctiva_c;
        this.pctiva_d=pctiva_d;
        this.status_cobro=status_cobro;
        this.tipodocumento=tipodocumento;
        this.contable=contable;
        this.numeroz=numeroz;
        this.status_impresion=status_impresion;
        this.codigoruta=codigoruta;
    }
}